USE [master]
GO

/****** Object:  Database [RentAWhipDatabase]    Script Date: 7.03.2021 16:18:17 ******/
CREATE DATABASE [RentAWhipDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RentAWhipDatabase', FILENAME = N'C:\Users\ofaru\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\RentAWhipDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RentAWhipDatabase_log', FILENAME = N'C:\Users\ofaru\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\RentAWhipDatabase.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RentAWhipDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RentAWhipDatabase] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [RentAWhipDatabase] SET ANSI_NULLS ON 
GO

ALTER DATABASE [RentAWhipDatabase] SET ANSI_PADDING ON 
GO

ALTER DATABASE [RentAWhipDatabase] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [RentAWhipDatabase] SET ARITHABORT ON 
GO

ALTER DATABASE [RentAWhipDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RentAWhipDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [RentAWhipDatabase] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [RentAWhipDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [RentAWhipDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RentAWhipDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RentAWhipDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [RentAWhipDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [RentAWhipDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RentAWhipDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RentAWhipDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RentAWhipDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RentAWhipDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RentAWhipDatabase] SET QUERY_STORE = OFF
GO

USE [RentAWhipDatabase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [RentAWhipDatabase] SET  READ_WRITE 
GO

